# Generated by Django 4.1.5 on 2023-01-21 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insure_Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='no package_name', max_length=200)),
                ('price', models.CharField(default='no price', max_length=200)),
                ('description', models.CharField(default='no description', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='no type', max_length=100)),
                ('pet_name', models.CharField(default='no pet_name', max_length=200)),
                ('species', models.CharField(default='no species', max_length=200)),
                ('image_url', models.CharField(default='no image_url', max_length=600)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateTimeField()),
                ('package_id', models.ForeignKey(default='no package_id', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets_insure.insure_package')),
                ('user_id', models.ForeignKey(default='no user_id', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
