# Generated by Django 4.1.5 on 2023-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_insure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(default='no type', max_length=100),
        ),
    ]
